### PR TITLE
fix(icons): Icon path must be relative to plugin registry root folder

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Cherry-pick of https://github.com/redhat-developer/codeready-workspaces/pull/505 in 2.9

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1840

### CODE REVIEW

**Comment by vitaliy-guliy** [comment]
@ericwill @svor @nickboldt

**Comment by nickboldt** [comment]
OK so the options here:
* resubmit the PR using a branch against the origin, instead of your fork
* ignore the failing tests and hope for the best.

**Comment by vitaliy-guliy** [comment]
> OK so the options here:
> 
> * resubmit the PR using a branch against the origin, instead of your fork
> * ignore the failing tests and hope for the best.

I don't have permissions on create branches.
If somebody give me them, I will resubmit this PR.

**Comment by vitaliy-guliy** [comment]
Superseded by https://github.com/redhat-developer/codeready-workspaces/pull/519

**Pull request closed without merging**
