### PR TITLE
CRW-136 attempt to use 1.0.1 version for CRW...

### PR DESCRIPTION
**Pull request by nickboldt**
CRW-136 attempt to use 1.0.1 version for CRW while still depending on Che 6.19.0-SNAPSHOT

Change-Id: If18df646ed14fc9a7605a1a5d989c91b3c5260b7
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
testPR

**Comment by SkorikSergey** [comment]
testPR

**Comment by SkorikSergey** [comment]
Can one of the admins verify this patch?

**Comment by nickboldt** [comment]
Already merged.

**Pull request closed without merging**
