### PR TITLE
[2.8] Adapt CRW to the new dashboard

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This PR cleans up product.json in the same way as it's done for new Dashboard.

P.S. Workspace loader will be removed in a separate PR.

### What issues does this PR fix or reference?
It follows up https://github.com/eclipse/che/pull/18549
It's done for switching to Dashboard Next https://issues.redhat.com/browse/CRW-1435

### CODE REVIEW

**Comment by nickboldt** [comment]
I assume this shouldn't be merged before 2.7, since we won't be including dashboard next in CRW 2.6. 

Correct?

**Comment by nickboldt** [comment]
Tried a quick build of CRW server from Che master branch in this job and it failed because the file I'm trying to sed no longer exists:

```
17:37:01 + sed -r -i -e 's#(.+productVersion = ).+#\1'\''2.8.0.GA :: CRW_CI/crw-server_2.x/2 :: che-dev @ 9348 (19) :: che-parent @ a6dd7f (7.15.0) :: che @ a01e3 (7.27.0-SNAPSHOT) :: codeready-workspaces @ 05b7 (2.8.0.GA)'\'';#g' che-dashboard/src/components/api/che-service.factory.ts
17:37:01 sed: can't read che-dashboard/src/components/api/che-service.factory.ts: No such file or directory
```

-- https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-server_2.x/2/console

Is there an equivalent place to set the product version in the new dashboard? 

```
// insert a longer version string which includes both CRW and Che, plus build and SHA info
sh "sed -r -i -e \"s#(.+productVersion = ).+#\\1'${CRW_SHAs}';#g\" ${CHE_DB_path}/src/components/api/che-service.factory.ts"
sh "egrep 'productVersion = ' ${CHE_DB_path}/src/components/api/che-service.factory.ts"

```

-- https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/blob/master/jobs/CRW_CI/crw-server_2.jenkinsfile#L136-138

**Comment by sleshchenko** [comment]
> Is there an equivalent place to set the product version in the new dashboard?

The version is supposed to be set via product.json https://github.com/redhat-developer/codeready-workspaces/pull/403/files#diff-6f159b8eced95e7451d4af0c7d5f434462dd0b99b2f914281c8efdab6e0116c3L4
I did not get why we should do replacement in source code.

**Comment by nickboldt** [comment]
MR to fix both the above problem and remove the ws-loader from the CRW server build:

https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/345/diffs

**Comment by nickboldt** [comment]
@sleshchenko if wsloader is no longer needed in CRW server... why are we still building and releasing it https://github.com/eclipse/che-workspace-loader/ ?

**Comment by nickboldt** [comment]
merged and building in https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-server_2.x/3/console

**Comment by nickboldt** [comment]
Failed. Followup work in https://issues.redhat.com/browse/CRW-1644

**Pull request merged**
