### PR TITLE
fix: add v3/plugins/.htaccess file back into Dockerfile

### PR DESCRIPTION
**Pull request by ericwill**
Signed-off-by: Eric Williams <ericwill@redhat.com>

### What does this PR do?
Make sure the .htaccess file is copied in, it went missing in the recent plugin registry automation changes.

### What issues does this PR fix or reference?
Part of CRW-1886

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by JPinkney — APPROVED** [review]

**Comment by sleshchenko** [comment]
side-comment, does CRW repos need Conventional Commits? Probably yes

**Comment by benoitf** [comment]
is that images folder is also there ?
https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/v3/images/eclipse-che-logo.png

**Comment by ericwill** [comment]
> is that images folder is also there ?
> https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/v3/images/eclipse-che-logo.png

I think you are replying to the wrong PR

**Comment by benoitf** [comment]
@ericwill I reply to the correct PR, just that I think we'll miss another file

```
$ docker run --rm -it --entrypoint=bash  quay.io/crw/pluginregistry-rhel8:2.9-20 -c "ls -la /var/www/html/v3/images/"
```

there is no eclipse-che-logo there

**Review by nickboldt — APPROVED** [review]

**Comment by benoitf** [comment]
it's this upstream line
https://github.com/eclipse-che/che-plugin-registry/blob/master/build/dockerfiles/Dockerfile#L26

**Comment by ericwill** [comment]
> @ericwill I reply to the correct PR, just that I think we'll miss another file
> 
> ```
> $ docker run --rm -it --entrypoint=bash  quay.io/crw/pluginregistry-rhel8:2.9-20 -c "ls -la /var/www/html/v3/images/"
> ```
> 
> there is no eclipse-che-logo there

Ah okay. There is another PR for icons open already, we'll handle it there

**Comment by nickboldt** [comment]
> side-comment, does CRW repos need Conventional Commits? Probably yes

NEED? No. You can use semantic comments even if you're not forced to do so. 
If this PR was called "fix: ..." or "bug: ..." would you know significantly more about it than you do? 

I'd argue calling it "CRW-1886 ..." would be more valuable but I'm pretty good at forgetting to do that myself :)

But if someone wants to enable semantic commit pr checking here, have at it.

**Review by benoitf — APPROVED** [review]
we're missing another icon file but it'll handle in another PR

**Pull request merged**
