### PR TITLE
rename commands to start Quarkus in dev mode

### PR DESCRIPTION
**Pull request by sunix**
based on the terminology used in https://quarkus.io/guides/getting-started#development-mode

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-701

### CODE REVIEW

**Comment by nickboldt** [comment]
+1, but will let @svor comment too

**Comment by svor** [comment]
the name looks a bit long, but i like the meaning
screenshot-che openshift io-2020 03 23-10_51_37

**Comment by sunix** [comment]
"Start Quarkus in devmode (hot deploy + debug)" ?

**Comment by svor** [comment]
I like that

**Pull request merged**
