### PR TITLE
CRW-193 rename Java EAP to JBoss...

### PR DESCRIPTION
**Pull request by nickboldt**
CRW-193 rename Java EAP to JBoss EAP

Change-Id: Id217bcd8683ec4a213869d1f2ed3c657023c8b99
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by eivantsov** [comment]
@dmytro-ndp this PR does not change stack ID, only name. How does it impact tests?

**Comment by dmytro-ndp** [comment]
@eivantsov: each E2E user stories test linked with exact stack and have corresponding name. Consequently, we need to change corresponding e2e user story test name `JavaEapUserStoryTest` to `JBossEapUserStoryTest` to avoid misleading.
The same is for the constant `com.redhat.codeready.selenium.pageobject.dashboard.CodereadyStacks.JAVA_EAP` > `com.redhat.codeready.selenium.pageobject.dashboard.CodereadyStacks.JBOSS_EAP`

----

I will fix it myself.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
After 2h20 mins your verification job is still going. And in recent history, it's never been green, so I'm not sure I trust it to tell me if this is a breaking change. https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test-OCP/buildTimeTrend

**Pull request closed without merging**
