### PR TITLE
Selenium: add a test suite for checking basic Codeready functionality

### PR DESCRIPTION
**Pull request by SkorikSergey**

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
IMHO, regression e2e tests ought to cover supporting stacks only:
- JavaUserStoryTest
- NodeJsUserStoryTest

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP:
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/40/)
[Test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/40//E2E_20tests_20report/)

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP:
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/41/)
[Test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/41//E2E_20tests_20report/)

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP:
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/42/)
[Test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/42//E2E_20tests_20report/)

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP:
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/43/)
[Test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/43//E2E_20tests_20report/)
docker image: quay.io/crw_pr/server:pr108

**Comment by dmytro-ndp** [comment]
There is flaky test in suite. At the same time we should have 100% result for PR without regression.

**Comment by dmytro-ndp** [comment]
You can mark test as FLAKY to execute it from the test execution automatically

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP:
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/44/)
[Test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/44//E2E_20tests_20report/)
docker image: quay.io/crw_pr/server:pr108

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP:
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/45/)
[Test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/codeready-pr-test/45//E2E_20tests_20report/)
docker image: quay.io/crw_pr/server:pr108

**Pull request closed without merging**
