### PR TITLE
Update vscode-xml

### PR DESCRIPTION
**Pull request by ericwill**
Signed-off-by: Eric Williams <ericwill@redhat.com>

### What does this PR do?
* Use .vsix file built by codeready-workspaces-vscode-extensions builder
* Update the plugin to 0.14.0

### What issues does this PR fix or reference?
Fixes CRW-1337

#### Release Notes

N/A

#### Docs PR (if applicable)

N/A

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]
+1, but would prefer to know if @apupier has any concerns w/ this new version... since we can't test it until the sidecar exists 

(I guess you can test using the 2.5 image until the 2.6 one exists)

**Comment by apupier** [comment]
I do not have access to a Codeready Workspaces instance (and doesn't have time to setup one locally)

The pointed vsix contains the language server jar in the server folder. (which was the reason of the previous failure that i'm aware of).
I tried the vsix in my local VS Code instance and it is working fine.

**Comment by ericwill** [comment]
Upstream [PR](https://github.com/eclipse/che-plugin-registry/pull/707) merged/validated. We can merge this one once the sidecar image is available.

**Comment by nickboldt** [comment]
Should have https://quay.io/repository/crw/plugin-java11-rhel8?tag=2.6&tab=tags available soon but won't have version on registry.redhat.io until we GA in Feb.

Can you rebase this?

**Comment by ericwill** [comment]
> Should have https://quay.io/repository/crw/plugin-java11-rhel8?tag=2.6&tab=tags available soon but won't have version on registry.redhat.io until we GA in Feb.
> 
> Can you rebase this?

Done

**Pull request merged**
