### PR TITLE
fix(java): make java8 plugin executable

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>

### What does this PR do?
Add a command to run executable endpoint for redhat/java8 plugin

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/CRW-1923

### CODE REVIEW

**Comment by nickboldt** [comment]
is this change required for other plugins too? Why is only java8 impacted?

**Comment by svor** [comment]
> is this change required for other plugins too? Why is only java8 impacted?

@nickboldt because there is a difference between java8 plugin in [2.9](https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/che-theia-plugins.yaml#L337) and [2.8](https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.8-rhel-8/dependencies/che-plugin-registry/v3/plugins/redhat/java8/0.63.0/meta.yaml), probably it was missed when we made plugin's refactoring

**Review by nickboldt — APPROVED** [review]
seems legit. If Eric has no objections, then feel free to merge this into 2.9 and 2 branches, and trigger a 2.9 build (2.x jobs are currently disabled to save QE PSI testing resources).

**Comment by benoitf** [comment]
about that change, as we need to apply the changes on all che-theia-plugins sidecars (as we reuse same image in devfile and plug-ins) maybe we need an extra flag on plug-in registry generator to add that on all sidecars.
(I see no value adding that in every entries of che-theia-plugins.yaml and it's leading to maintenance errors)

**Comment by svor** [comment]
> about that change, as we need to apply the changes on all che-theia-plugins sidecars (as we reuse same image in devfile and plug-ins) maybe we need an extra flag on plug-in registry generator to add that on all sidecars.
> (I see no value adding that in every entries of che-theia-plugins.yaml and it's leading to maintenance errors)

@benoitf @nickboldt @ericwill I've created an issue to move this functionality from che-theia-plugins.yaml https://issues.redhat.com/browse/CRW-1924

**Pull request merged**
