### PR TITLE
Add gradle volume; Add command to run endpoint

### PR DESCRIPTION
**Pull request by svor**
-  Adds a command to run endpoint into java11 plugins
-  Adds a volume for ~/.gradle folder into plugins where plugin-java11-rhel8:2.1 is used

### CODE REVIEW

**Comment by svor** [comment]
@nickboldt take a look pls

**Comment by nickboldt** [comment]
BTW according to @amisevsk in https://github.com/eclipse/che-jwtproxy/pull/20/files#r385727728

"Unsure if it's a plus or minus, but having a volume in the dockerfile means (some) OpenShift clusters will show an error event if the pod doesn't mount a corresponding volume in the podspec. If the volumes used are different between the two dockerfiles though, it'll make it hard to switch a deployment to use the rhel version."

**Comment by svor** [comment]
@nickboldt That comment was about the volume in **Dockerfile** but this PR is about **Devfile**

**Comment by nickboldt** [comment]
ah, good point. Thanks for setting me straight :D

**Pull request merged**
