### PR TITLE
[WIP] Convert midstream repo to use upstream plugin registry automation

### PR DESCRIPTION
**Pull request by ericwill**
:no_entry_sign:  Do not merge until CRW 2.8 is released! :no_entry_sign: 

Signed-off-by: Eric Williams <ericwill@redhat.com>

### What does this PR do?
Introduces the plugin registry automation from upstream into the midstream repository.

### What issues does this PR fix or reference?
Part of [CRW-1648](https://issues.redhat.com/browse/CRW-1648)

### CODE REVIEW

**Comment by ericwill** [comment]
This is a work in progress, not quite ready yet.

**Comment by benoitf** [comment]
I think it will require https://github.com/eclipse/che/issues/18571 (yarn2 enabling) to make it happy on offline brew

**Comment by ericwill** [comment]
> I think it will require [eclipse/che#18571](https://github.com/eclipse/che/issues/18571) (yarn2 enabling) to make it happy on offline brew

Yes I believe you are correct. Something for next sprint :+1:

**Comment by nickboldt** [comment]
+1 for whatever makes it easier to fetch deps into an offline cache for reuse in brew. `go mod vendor` is nice, and if yarn2 can do the same, that's awesome.

**Comment by ericwill** [comment]
Closing this and will reopen with a non-fork branch to get working CI.

**Pull request closed without merging**
