### PR TITLE
[Selenium] Remove java selenium tests

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Java selenium tests were removed from upstream - https://github.com/eclipse/che/pull/19519.

### CODE REVIEW

**Review by dmytro-ndp — APPROVED** [review]
Looks good to me.

**Review by nickboldt — APPROVED** [review]
"After new Dashboard releasing we no longer use java Selenium tests. Therefore, we need to delete all tasks related to java tests on centos.ci."

+1 from me...

but do we have new dashboard tests to replace these?

**Comment by SkorikSergey** [comment]
> "After new Dashboard releasing we no longer use java Selenium tests. Therefore, we need to delete all tasks related to java tests on centos.ci."
> 
> +1 from me...
> 
> but do we have new dashboard tests to replace these?

Typescript tests from upstream and [e2e-codeready](https://gitlab.cee.redhat.com/codeready-workspaces/e2e-codeready) partially replace java tests.

**Comment by nickboldt** [comment]
did you want this merged into the 2.8 branch too?

**Comment by SkorikSergey** [comment]
> did you want this merged into the 2.8 branch too?

Maybe yes. We no longer use java tests in CRW pre-release testing.

**Pull request merged**
