### PR TITLE
chore: CRW-1157 don't use USE_DIGESTS...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: CRW-1157 don't use USE_DIGESTS boolean anymore as we no longer generate digests in the registries

Change-Id: I697975a67fcd23c2401299f94ddd0c33540207fe
Signed-off-by: nickboldt <nboldt@redhat.com>

chore: CRW-1157 remove write_image_digests.sh as digests are now swapped in at runtime via entrypoint.sh

Change-Id: I3c968b1854e2d8d883386a36ce3eedb33a6b8f1e
Signed-off-by: nickboldt <nboldt@redhat.com>

CRW-1157 remove references to digests from build scripts, readmes, and devfiles

Change-Id: Ic42b003716303793046acf3da849753de2007617
Signed-off-by: nickboldt <nboldt@redhat.com>

CRW-1157 enable --skip-digest-generation:true for all plugin reg builds

Change-Id: Ic9c2d8a6161b58e023c5ffdad462537eb00401ac
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
Plugin registry docs will need to be updated just FYI

**Comment by nickboldt** [comment]
> Plugin and devfile registry docs will need to be updated just FYI

You mean downstream? please amend my PR with changes! :D 

Or if upstream, point me at where to make the change?

**Review by amisevsk — APPROVED** [review]
LGTM

**Review by svor — APPROVED** [review]

**Comment by ericwill** [comment]
You can disregard my comments -- I thought the `--use-digests` option was specified in our custom registry docs, but it isn't

**Comment by nickboldt** [comment]
cherrypicked to 2.x/2.12 branch too

**Pull request merged**
