### PR TITLE
feat(java): upgrade java extension to 0.75.0 and quarkus to v1.7.0

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
upgrade java extension to 0.75.0 and quarkus to v1.7.0
also adding the microprofile extension which is a requirement for quarkus extension

### What issues does this PR fix or reference?
Quarkus: https://issues.redhat.com/browse/CRW-1697
Java: https://issues.redhat.com/browse/CRW-1699
upstream PR:
- Quarkus https://github.com/eclipse-che/che-plugin-registry/pull/650
- Java https://github.com/eclipse-che/che-plugin-registry/pull/890

### CODE REVIEW

**Comment by nickboldt** [comment]
Has this been verified against openj9?

**Review by nickboldt — APPROVED** [review]
I suspect @benoitf will reject this because it doesn't conform to the issue template and doesn't mention a JIRA. 

(I'm more flexible, but also like to see a JIRA # linked from PRs when possible.) :)

**Comment by sunix** [comment]
> Has this been verified against openj9?

I have not tested with openj9 but as these ones are not impacting the sidecars it should be ok.

**Comment by sunix** [comment]
please do not merge yet, there is a problem (strangely the extension works after a refresh)
Selection_395

**Comment by svor** [comment]
@sunix the problem could be related to https://issues.redhat.com/browse/CRW-1793

**Comment by sunix** [comment]
Yes unrelated to my changes I have just tested without and have the same issue. This is ok !

**Review by svor — APPROVED** [review]

**Pull request merged**
