### PR TITLE
fix: Move devfile templates generation to build.sh

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
In order to fix the Jenkins build, move the devfile v2 templates generation script to `./build.sh`

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-2500

### CODE REVIEW

**Comment by svor** [comment]
Probably it should be synched with https://github.com/redhat-developer/codeready-workspaces-images/blob/c5b9ee2b4d22fb698d0a9363a08cc265e7acf099/codeready-workspaces-devfileregistry/build.sh.
@nickboldt please correct me if I'm wrong

**Review by nickboldt — APPROVED** [review]
seems reasonable.

**Comment by nickboldt** [comment]
triggered build https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/CRW_CI/job/crw-devfileregistry_2.x/793/console to test if this works...

**Comment by nickboldt** [comment]
> Probably it should be synched with https://github.com/redhat-developer/codeready-workspaces-images/blob/c5b9ee2b4d22fb698d0a9363a08cc265e7acf099/codeready-workspaces-devfileregistry/build.sh. @nickboldt please correct me if I'm wrong

Yes, and the jenkins jobs do that for us:

* https://github.com/redhat-developer/codeready-workspaces-images/commit/e7fffdff163a59e51018bac31f8f38535b25d809 -> https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-devfileregistry/build.sh

**Pull request merged**
