### PR TITLE
CRW-14 replace 'DEVELOPER' with 'CODEREADY...

### PR DESCRIPTION
**Pull request by nickboldt**
replace 'DEVELOPER' with 'CODEREADY WORKSPACES' in the two product-named svg files; remove unreferenced branding.css and redhat-logo.svg files to a DEPRECATED/ folder pending deletion

Change-Id: Ie9c29fc56f87b5e31d55b292815be2f90685195c
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
Fixed LOGO looks too small, IMHO
screenshot from 2018-12-20 18-35-58

**Comment by dmytro-ndp** [comment]
Here is other logo for ide: https://github.com/redhat-developer/codeready-workspaces/tree/master/ide/codeready-product-info/src/main/resources/com/redhat/codeready/plugin/product/info/client

**Comment by nickboldt** [comment]
@dmytro-ndp OK, here's a tweaked version of the svg files -- more space between CODEREADY and WORKSPACES. Also fixed the svg that sits in the middle of the workspace on initial startup.

https://github.com/redhat-developer/codeready-workspaces/pull/60/commits/e61b6c77b537b0bef063dbb6737973f0f3bff3ec

Please rebuild and see if this is better. I didn't resize the file used for the top left corner as based on MM chat, it seemed like you could simply make it bigger via code.

**Comment by nickboldt** [comment]
Weird. Not sure why inkscape would produce an invalid file. If I get time tonight I'll try again but otherwise I'm on PTO until Jan 3. Maybe someone else can hack the svg file in the meantime, or else we wait until Erin Rooney is back from the shutdown and she fixes it using whatever tools Brand uses.

**Comment by eivantsov** [comment]
@nickboldt where are the svgs?

**Comment by nickboldt** [comment]
@eivantsov see email - sent you a copy of the SVGs from Brand.

**Comment by nickboldt** [comment]
I removed the sodipodi:docname info and all the inkscape:* metadata from the SVG files. AFAICT they build fine locally (`mvn clean install` works) and they render fine in Chrome:

* https://github.com/redhat-developer/codeready-workspaces/blob/f45611de189b391986c1980d953faf08180b2b04/ide/codeready-product-info/src/main/resources/com/redhat/codeready/plugin/product/info/client/logo/rhd-logo-buildinfo.svg

* https://github.com/redhat-developer/codeready-workspaces/blob/f45611de189b391986c1980d953faf08180b2b04/assembly/assembly-dashboard-war/src/main/webapp/assets/branding/RHD_full_logo_color_RGB_inverse.svg

* https://github.com/redhat-developer/codeready-workspaces/blob/f45611de189b391986c1980d953faf08180b2b04/assembly/assembly-dashboard-war/src/main/webapp/assets/branding/RHD_full_logo_black_RGB.svg

So I'm tempted to push this to master, respin in Jenkins/OSBS, and see what happens in the resulting container. (I can't figure out how to start up the stuff I've built locally, so I'm at the mercy of someone who can explain to me how to do that.)

**Comment by dmytro-ndp** [comment]
@nickboldt: there is a document about [how to install CRW locally using OKD 3.11] (https://docs.google.com/document/d/1dcIlWUT9a2o_HUJuAtu1ppdESBwq8qT8rldCujGjVyo/edit#heading=h.o40bqobk8u57).

**Comment by dmytro-ndp** [comment]
I recompile the CRW with new changes and don't see updated logo:
screenshot from 2019-01-08 13-52-24

**Comment by dmytro-ndp** [comment]
@nickboldt: sorry, I had outdated deployment script which deployed CRW improperly. 
After update I have seen logos in the correct place:
codeready workspaces dashboard 1

**Comment by nickboldt** [comment]
New PR should look like this:

screenshot from 2019-01-10 16-22-31

**Comment by nickboldt** [comment]
Here's the latest dashboard - I can't make the footer image any better. We've tried a number of things and it's either much, much smaller & harder to read, or it ends up blank.

So this is the best we're getting:

screenshot

Note also the favicon is now the Shadowman one, instead of RHD.

**Comment by nickboldt** [comment]
And for the loader, we now get this:

(it's a little faded on the screenshot, as it fades up to white then fades away)

screenshot

**Pull request merged**
