### PR TITLE
chore: #19953 add tech-preview tag to meta.yaml

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: #19953 add tech-preview tags and rh-supported tags to the meta.yaml files; move python up from TP to GA tile order (05 -> 04)

(step 1 of https://github.com/eclipse/che/issues/19953 )

Change-Id: Ib1d9a5bfd008e4793c052780276dea850d618f68
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19953

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
See also https://github.com/eclipse-che/che-devfile-registry/pull/523

**Review by amisevsk — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Comment by l0rd** [comment]
Having one tag prefixed with `rh-` and not the other one is weird. I would rather have `supported` and `tech-preview` or `rh-supported` and `rh-tech-preview`.

**Comment by nickboldt** [comment]
Given Angel doesn't want the supported tag at all, I've removed 'em.

**Review by amisevsk — APPROVED** [review]
LGTM

**Pull request merged**
