### PR TITLE
CRW-1502 rename java-jboss-fuse to...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

CRW-1502 rename java-jboss-fuse to java-fuse

Change-Id: I0108ea71124d051f0832745c61becc20bb5a006a
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit messasge above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by apupier — COMMENTED** [review]
i think it won't be visible to users but shouldn't we also rename the folder name 02_java-jboss-fuse?

There is also jboss which is used for the user.home and m2 volume but I guess this one depends n the container and cannot be changed easily.

**Review by svor — APPROVED** [review]
Probably it makes sense to rename parent folder as well

**Comment by nickboldt** [comment]
jboss in $HOME is because we used to have EAP in the java8 sidecar, so `registry.redhat.io/codeready-workspaces/plugin-java8-rhel8:2.6` uses that too.

If you want that changed in 2.7, please open a CRW JIRA  and we can move to /home/user instead of /home/jboss.

**Comment by nickboldt** [comment]
> Probably it makes sense to rename parent folder as well but in general LGTM

Agreed: https://github.com/redhat-developer/codeready-workspaces/pull/414/commits/03012e670749cbad96034a46e2af0bff282da38f

**Pull request merged**
