### PR TITLE
add alternative Jenkinsfile for building CRW...

### PR DESCRIPTION
**Pull request by nickboldt**
add alternative Jenkinsfile for building CRW PR

Change-Id: Ie3bed43f0e328e41e5ccd6e22d4489d7b679aa36
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
testPR

**Comment by SkorikSergey** [comment]
test post!

**Comment by nickboldt** [comment]
testPR

**Pull request merged**
