### PR TITLE
Patch version of the Dashboard

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Patches version of the Dashboard.
Upstream related changes were merged in https://github.com/eclipse/che/pull/16406

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-673

#### Is it tested? How?
Not fully. I mean I've done:
```bash
export JOB_NAME="sleshche-local"
export BUILD_NUMBER=1
export GIT_COMMIT=123456
export GIT_BRANCH=patchedVersion
mvn clean install
```
and checked that the build tomcat.zip contains patched version but I have not built and deploy CRW to check if Dashboard displays it
Screenshot_20200320_090628

### CODE REVIEW

**Comment by nickboldt** [comment]
thanks, this looks good. 

but it requires a new build of che-server 7.9.3, right?

**Comment by dmytro-ndp** [comment]
We haven't released che-server:7.9.2. So, it could be included into it, IMHO.

**Comment by nickboldt** [comment]
OK then we need a 7.9.2.RC2 build that includes https://github.com/eclipse/che/pull/16406 and anything else in 7.9.x branch. @vparfonov @mkuznyetsov can you respin 7.9.2?

**Comment by nickboldt** [comment]
I can merge this if you think we need it but based on https://issues.redhat.com/browse/CRW-673?focusedCommentId=14005214&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14005214 seems like we don't need it. :)

**Comment by sleshchenko** [comment]
>  seems like we don't need it. :)

I believe it's needed! The previous solution is not stable and kind of magic. You can rely on that on your own risk

**Pull request merged**
