### PR TITLE
Add resource limits/requests to the plugins

### PR DESCRIPTION
**Pull request by svor**
### What does this PR do?
Adds `cpuLimit` and `cpuRequest` into plugin yamls. All values were ported from the upstream.

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1637

### CODE REVIEW

**Comment by ghatwala** [comment]
@svor  - generic query about this - how did you find/calculate/deduce on the values mentioned in all plugins here ? Am guessing unless we try these on all arches , we wouldn't know , correct ? : ) 
```
cpuLimit: xxm
cpuRequest: xxm
```

**Comment by svor** [comment]
> @svor - generic query about this - how did you find/calculate/deduce on the values mentioned in all plugins here ? Am guessing unless we try these on all arches , we wouldn't know , correct ? : )

@ghatwala this investigation was done in the upstream https://github.com/eclipse-che/che-plugin-registry/pull/774. And you are right we should tests these changes on all arches to guarantee that it doesn't break anything.

**Review by ghatwala — COMMENTED** [review]
+1 , for trying these on all arches, to check if it breaks anywhere .

**Comment by nickboldt** [comment]
I'm +1 to merge this but was just wondering what the units are and what these actually do...

```
cpuLimit: 500m
cpuRequest: 30m
```

Does that mean this plugin will ask for a minimum of 0.030 and maximum of 0.500 virtual CPUs? Is the "m" for milli, as in 1/1000th of a virtual CPU?

**Comment by ericwill** [comment]
> I'm +1 to merge this but was just wondering what the units are and what these actually do...
> 
> ```
> cpuLimit: 500m
> cpuRequest: 30m
> ```
> 
> Does that mean this plugin will ask for a minimum of 0.030 and maximum of 0.500 virtual CPUs? Is the "m" for milli, as in 1/1000th of a virtual CPU?

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu

Basically the `m` stands for millicores, so 100m is 0.1 of a CPU core/hyperthread

**Comment by svor** [comment]
@nickboldt 
cpuLimit -> to make sure that container never go above the value
cpuRequest -> is what guaranteed by k8s

**Comment by nickboldt** [comment]
cherrypicked to 2.8 branch as 28fd926e

**Pull request merged**
