### PR TITLE
CRW-136 use 1.0.1 version for CRW while still depending on Che 6.18

### PR DESCRIPTION
**Pull request by nickboldt**
CRW-136 use 1.0.1 version for CRW while still depending on Che 6.18 
remove versions from depmanaged deps

Change-Id: Ia0f4fb5d1275ba3e629dc7c575a0d53db049eb7a
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by SkorikSergey** [comment]
testPR

**Comment by SkorikSergey** [comment]
testPR

**Comment by SkorikSergey** [comment]
Can one of the admins verify this patch?

**Comment by nickboldt** [comment]
Already merged.

**Pull request closed without merging**
