### PR TITLE
Add dotnet, java maven and jboss devfiles

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>

Adds several devfiles:
-  dotnet with [dotnet-web-simple](https://github.com/che-samples/dotnet-web-simple) application
-  java-maven with [console-java-simple](https://github.com/che-samples/console-java-simple.git) application
-  java-eap-maven with [kitchensink-example](https://github.com/che-samples/kitchensink-example.git)
- java-eap-thorntail with [rest-http-redhat](https://github.com/thorntail-examples/rest-http-redhat) application

### CODE REVIEW

**Comment by svor** [comment]
@nickboldt it is ready to review

**Comment by svor** [comment]
@nickboldt it is ready to review

**Comment by nickboldt** [comment]
If you update your PR to the latest in master you can then run a build:

`docker build --no-cache -t quay.io/eclipse/che-devfile-registry:nightly -f build/dockerfiles/rhel.Dockerfile .`

And then use that devfile registry in your local Che to see how it behaves. 

Meanwhile I notice that the java-maven config is different from the upstream one:

image

Do we need the same JAVA_OPTS and JAVA_TOOL_OPTIONS? or are those only for JDK 11? 

Also are we sure redhat/java/latest will always be JDK 8? maybe it's better to use `redhat/java8/latest` plugin instead?

**Comment by svor** [comment]
Updated

**Pull request merged**
